---
apiVersion: v1
kind: Pod
metadata:
  name: tor-relays-1
  labels:
    tor_relay: "1"
spec:
  containers:
  - name: tor-relay-1
    image: quay.io/conorsch/tor-relay:latest
    env:
    - name: RELAY_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: tor-relay-config-1
          key: RELAY_ADDRESS
    - name: RELAY_PORT
      value: "9001"
    - name: RELAY_NICKNAME
      value: Emolument

  - name: tor-relay-2
    image: quay.io/conorsch/tor-relay:latest
    env:
    - name: RELAY_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: tor-relay-config-1
          key: RELAY_ADDRESS
    - name: RELAY_PORT
      value: "9002"
    - name: RELAY_NICKNAME
      value: Endeavor
