---
apiVersion: v1
kind: Pod
metadata:
  name: tor-relays-2
  labels:
    tor_relay: "2"
spec:
  containers:
  - name: tor-relay-3
    image: quay.io/conorsch/tor-relay:latest
    env:
    - name: RELAY_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: tor-relay-config-2
          key: RELAY_ADDRESS
    - name: RELAY_PORT
      value: "9003"
    - name: RELAY_NICKNAME
      value: Eritrea

  - name: tor-relay-4
    image: quay.io/conorsch/tor-relay:latest
    env:
    - name: RELAY_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: tor-relay-config-2
          key: RELAY_ADDRESS
    - name: RELAY_PORT
      value: "9004"
    - name: RELAY_NICKNAME
      value: Eyrie
