---
apiVersion: v1
kind: Pod
metadata:
  name: tor-relays-2
  labels:
    tor_relay: "2"
spec:
  containers:
  - name: tor-relay-3
    image: us.gcr.io/xenon-petal-208819/tor-relay:latest
    env:
    - name: RELAY_ADDRESS
      value: "104.199.126.85"
    - name: RELAY_PORT
      value: "9003"
    - name: RELAY_NICKNAME
      value: Eritrea

  - name: tor-relay-4
    image: us.gcr.io/xenon-petal-208819/tor-relay:latest
    env:
    - name: RELAY_ADDRESS
      value: "104.199.126.85"
    - name: RELAY_PORT
      value: "9004"
    - name: RELAY_NICKNAME
      value: Eyrie
