---
apiVersion: v1
kind: Service
metadata:
  name: tor-relay-lb-1
spec:
  ports:
  - name: tor-relay-1
    port: 9001
    targetPort: 9001
  - name: tor-relay-2
    port: 9002
    targetPort: 9002
  selector:
    tor_relay: "1"
  type: LoadBalancer
  externalTrafficPolicy: Local
